export const siteConfig = {
  name: "OpenClaw Pro",
  description: "OpenClaw 中文进阶培训平台 — 从零到精通，系统化学习 AI Agent",
  url: "https://openclawpro.dev",
  ogImage: "https://openclawpro.dev/og.png",
  links: {
    github: "https://github.com/openclawpro",
    discord: "https://discord.gg/openclaw",
    telegram: "https://t.me/openclaw",
  },
};

export const navItems = [
  {
    title: "免费教程",
    href: "/learn",
    children: [
      { title: "7天入门路径", href: "/learn/day/1", description: "从零开始，7天掌握 OpenClaw 核心功能" },
      { title: "专题教程", href: "/learn/topics", description: "按场景分类的中深度实战教程" },
      { title: "技能库导航", href: "/learn/skills", description: "精选技能推荐，带中文详评和使用指南" },
    ],
  },
  { title: "精品课程", href: "/courses" },
  {
    title: "实战案例",
    href: "/cases",
    children: [
      { title: "个人效率", href: "/cases/productivity" },
      { title: "开发者工具", href: "/cases/developer" },
      { title: "企业自动化", href: "/cases/enterprise" },
      { title: "创意玩法", href: "/cases/creative" },
    ],
  },
  { title: "资源中心", href: "/resources" },
  { title: "社区", href: "/community" },
  { title: "企业服务", href: "/enterprise" },
  { title: "博客", href: "/blog" },
] as const;

export const stats = [
  { label: "教程", value: "333+" },
  { label: "天学习路径", value: "7" },
  { label: "学员", value: "2000+" },
  { label: "企业服务", value: "50+" },
] as const;

export const courses = [
  {
    slug: "zero-to-hero",
    title: "OpenClaw 零基础训练营",
    description: "系统入门，20 节视频带你从零掌握 OpenClaw 核心功能",
    price: 199,
    originalPrice: 299,
    difficulty: "入门" as const,
    lessons: 20,
    featured: true,
    coverImage: "/images/courses/zero-to-hero.jpg",
  },
  {
    slug: "automation-mastery",
    title: "OpenClaw 自动化实战",
    description: "30 节进阶视频，深入自动化工作流、Cron 任务和 API 集成",
    price: 399,
    originalPrice: 599,
    difficulty: "进阶" as const,
    lessons: 30,
    featured: true,
    coverImage: "/images/courses/automation.jpg",
  },
  {
    slug: "skill-developer",
    title: "Skill 开发者课程",
    description: "25 节高级课程，学会开发自定义 Skill 和 MCP Server",
    price: 599,
    originalPrice: 799,
    difficulty: "高级" as const,
    lessons: 25,
    featured: true,
    coverImage: "/images/courses/skill-dev.jpg",
  },
  {
    slug: "enterprise-agent",
    title: "企业级 AI Agent 架构",
    description: "15 节企业实战课，Multi-Agent 架构设计与落地方案",
    price: 999,
    originalPrice: 1299,
    difficulty: "高级" as const,
    lessons: 15,
    featured: false,
    coverImage: "/images/courses/enterprise.jpg",
  },
] as const;

export const dayTopics = [
  { day: 1, title: "认识 OpenClaw", description: "什么是 AI 助手 + 安装部署", icon: "🚀" },
  { day: 2, title: "深度对话", description: "Prompt 技巧 + Workspace 配置", icon: "💬" },
  { day: 3, title: "文件与代码", description: "文件操作 + 代码生成基础", icon: "📁" },
  { day: 4, title: "联网能力", description: "搜索 + API 调用", icon: "🌐" },
  { day: 5, title: "技能扩展", description: "ClawHub 技能安装", icon: "🧩" },
  { day: 6, title: "自动化", description: "Cron + Heartbeat 定时任务", icon: "⚡" },
  { day: 7, title: "高级玩法", description: "多 Agent + 浏览器控制", icon: "🎯" },
] as const;

export const skillCategories = [
  { id: "featured", label: "编辑精选 Top 20", icon: "🏆" },
  { id: "office", label: "办公效率", icon: "💼" },
  { id: "developer", label: "开发者工具", icon: "🛠️" },
  { id: "info", label: "信息获取", icon: "🌐" },
  { id: "marketing", label: "营销增长", icon: "📈" },
  { id: "smarthome", label: "智能家居", icon: "🏠" },
  { id: "media", label: "音视频", icon: "🎵" },
  { id: "ai", label: "AI & LLM", icon: "🧠" },
  { id: "messaging", label: "通讯平台", icon: "💬" },
  { id: "fun", label: "趣味玩法", icon: "🎮" },
] as const;

export const sampleSkills = [
  {
    name: "homeassistant",
    title: "智能家居控制",
    description: "让 OpenClaw 直接控制你的 Home Assistant 设备，实现语音/消息控制灯光、空调、窗帘等。支持场景联动和自动化触发。",
    review: "实测下来最稳定的智能家居 Skill，但需要 Home Assistant 已经配好。建议先看我们的部署教程再安装。",
    rating: 4,
    difficulty: "入门",
    category: "smarthome",
    installCommand: "openclaw skill install homeassistant",
    tags: ["智能家居", "生活自动化", "IoT"],
  },
  {
    name: "notion",
    title: "Notion 笔记管理",
    description: "通过 OpenClaw 直接创建、编辑和查询 Notion 页面和数据库。支持模板化创建和批量操作。",
    review: "办公效率类 Skill 中最推荐的一个，API 调用稳定。适合用 Notion 做知识库的用户。",
    rating: 5,
    difficulty: "入门",
    category: "office",
    installCommand: "openclaw skill install notion",
    tags: ["笔记", "知识管理", "办公效率"],
  },
  {
    name: "github",
    title: "GitHub 代码管理",
    description: "通过 OpenClaw 管理 GitHub 仓库，包括创建 Issue、PR Review、代码搜索和 CI/CD 监控。",
    review: "开发者必装 Skill。配合 Claude Code 使用体验极佳，但需要正确配置 GitHub Token 权限。",
    rating: 5,
    difficulty: "进阶",
    category: "developer",
    installCommand: "openclaw skill install github",
    tags: ["代码管理", "DevOps", "CI/CD"],
  },
  {
    name: "telegram",
    title: "Telegram 消息助手",
    description: "通过 Telegram Bot 与 OpenClaw 交互，支持消息推送、自动回复、群组管理和 Inline Keyboard 交互。",
    review: "消息平台类 Skill 的首选。配置简单，功能全面，延迟极低。推荐所有海外用户安装。",
    rating: 5,
    difficulty: "入门",
    category: "messaging",
    installCommand: "openclaw skill install telegram",
    tags: ["Telegram", "消息推送", "Bot"],
  },
  {
    name: "web-scraper",
    title: "智能网页抓取",
    description: "自动抓取网页内容、提取结构化数据、监控页面变化。支持 CSS 选择器和 AI 智能提取两种模式。",
    review: "非常强大的数据获取工具，AI 模式可以自动理解页面结构。但注意遵守目标网站的 robots.txt。",
    rating: 4,
    difficulty: "进阶",
    category: "info",
    installCommand: "openclaw skill install web-scraper",
    tags: ["网页抓取", "数据提取", "监控"],
  },
  {
    name: "gmail",
    title: "Gmail 邮件管理",
    description: "自动化 Gmail 收发邮件、智能分类、摘要生成和跟进提醒。支持 OAuth 授权，安全可靠。",
    review: "邮件处理最强 Skill，每天 200+ 封邮件轻松管理。AI 摘要功能非常实用，再也不怕漏掉重要邮件。",
    rating: 5,
    difficulty: "入门",
    category: "office",
    installCommand: "openclaw skill install gmail",
    tags: ["邮件", "Gmail", "办公效率"],
  },
  {
    name: "stable-diffusion",
    title: "AI 图像生成",
    description: "通过 OpenClaw 调用 Stable Diffusion、DALL-E、Midjourney API 生成图片，支持文生图、图生图、风格迁移。",
    review: "创意玩法的核心 Skill。多模型支持很方便，Prompt 模板功能特别好用。生成速度取决于你的 GPU 配置。",
    rating: 4,
    difficulty: "进阶",
    category: "ai",
    installCommand: "openclaw skill install stable-diffusion",
    tags: ["AI绘图", "图像生成", "创意"],
  },
  {
    name: "rss-reader",
    title: "RSS 新闻聚合",
    description: "订阅 RSS 源，AI 自动摘要和分类，生成每日简报并推送到你喜欢的平台。支持 OPML 批量导入。",
    review: "信息获取类必装 Skill。配合 Cron 定时任务使用效果最佳。推荐订阅 20-50 个高质量源。",
    rating: 4,
    difficulty: "入门",
    category: "info",
    installCommand: "openclaw skill install rss-reader",
    tags: ["RSS", "新闻", "信息聚合"],
  },
  {
    name: "calendar",
    title: "日程管理助手",
    description: "接入 Google Calendar / Outlook 日历，智能日程管理、冲突检测、会议准备和每日提醒。",
    review: "日常使用频率最高的 Skill 之一。每天早上的日程提醒已经成为我的固定流程，跨时区会议协调超方便。",
    rating: 4,
    difficulty: "入门",
    category: "office",
    installCommand: "openclaw skill install calendar",
    tags: ["日历", "日程", "提醒"],
  },
  {
    name: "docker-manager",
    title: "Docker 容器管理",
    description: "通过 OpenClaw 管理 Docker 容器，支持启停、日志查看、镜像更新、资源监控和 Compose 编排。",
    review: "运维利器。通过 Telegram 就能管理服务器上的容器，再也不用 SSH 登录了。安全配置请参考我们的教程。",
    rating: 4,
    difficulty: "进阶",
    category: "developer",
    installCommand: "openclaw skill install docker-manager",
    tags: ["Docker", "运维", "容器管理"],
  },
  {
    name: "wechat-bot",
    title: "微信消息助手",
    description: "通过企业微信或第三方桥接实现微信消息自动化，支持自动回复、群管理、定时推送。",
    review: "国内用户最关注的 Skill。企业微信方案最稳定推荐。个人微信方案需注意合规风险。",
    rating: 3,
    difficulty: "进阶",
    category: "messaging",
    installCommand: "openclaw skill install wechat-bot",
    tags: ["微信", "企业微信", "消息"],
  },
  {
    name: "tts-stt",
    title: "语音识别与合成",
    description: "集成 Whisper 语音识别和多种 TTS 引擎，支持语音输入、语音回复、会议转录和播客生成。",
    review: "音视频类最实用的 Skill。Whisper 识别准确率很高，TTS 支持多种音色。会议转录功能特别推荐。",
    rating: 4,
    difficulty: "进阶",
    category: "media",
    installCommand: "openclaw skill install tts-stt",
    tags: ["语音识别", "TTS", "Whisper"],
  },
  {
    name: "seo-analyzer",
    title: "SEO 分析助手",
    description: "自动分析网站 SEO 状态、关键词排名监控、竞品分析和内容优化建议。生成详细的 SEO 报告。",
    review: "营销人员的好帮手。定期自动生成 SEO 报告，关键词监控及时告警。配合内容生成 Skill 效果更佳。",
    rating: 4,
    difficulty: "进阶",
    category: "marketing",
    installCommand: "openclaw skill install seo-analyzer",
    tags: ["SEO", "营销", "分析"],
  },
  {
    name: "mini-game",
    title: "AI 小游戏合集",
    description: "与 OpenClaw 玩文字冒险、猜谜、角色扮演等互动小游戏。支持多人模式和排行榜。",
    review: "纯粹的趣味 Skill，休闲时候可以玩玩。AI 地下城探险特别上瘾，角色扮演的代入感很强。",
    rating: 3,
    difficulty: "入门",
    category: "fun",
    installCommand: "openclaw skill install mini-game",
    tags: ["游戏", "娱乐", "趣味"],
  },
] as const;

export const testimonials = [
  {
    name: "张明",
    role: "全栈工程师",
    content: "7天入门路径非常系统化，帮我快速理解了 OpenClaw 的核心概念。现在每天都在用它写代码、管理项目。",
    avatar: "/images/avatars/avatar-1.jpg",
  },
  {
    name: "李婷",
    role: "产品经理",
    content: "自动化实战课让我学会了用 OpenClaw 自动化日报生成和邮件管理，每天节省 2 小时，团队效率提升明显。",
    avatar: "/images/avatars/avatar-2.jpg",
  },
  {
    name: "王磊",
    role: "CTO @ 某 SaaS 公司",
    content: "企业级课程帮助我们团队落地了 AI Agent 架构，客服自动化节省了 80% 的人力成本，ROI 远超预期。",
    avatar: "/images/avatars/avatar-3.jpg",
  },
  {
    name: "陈晓",
    role: "独立开发者",
    content: "Skill 开发者课程太值了！学完后我已经在 ClawHub 发布了 3 个 Skill，其中一个月下载量超过 500。",
    avatar: "/images/avatars/avatar-4.jpg",
  },
  {
    name: "赵雨",
    role: "自媒体运营",
    content: "用 OpenClaw 管理 5 个平台的内容分发，从选题到发布全自动化。一个人干了三个人的活，老板都惊了。",
    avatar: "/images/avatars/avatar-5.jpg",
  },
  {
    name: "刘志远",
    role: "DevOps 工程师",
    content: "Docker 部署教程写得非常清楚，按照教程 30 分钟就搭好了。现在 CI/CD 监控全靠 OpenClaw 推送告警。",
    avatar: "/images/avatars/avatar-6.jpg",
  },
] as const;
